### ISSUE TITLE
Integrate Contributor Covenant or similar code of conduct

### ISSUE THREAD

**Issue by tommorris** [tommorris/mf2py#47]
I recently discovered [Contributor Covenant](http://contributor-covenant.org/). It's basically a Code of Conduct for contribution to FLOSS projects.

Unless there's any strong objections from frequent contributors, I'm going to suggest that we adopt [v1.1.0](http://contributor-covenant.org/version/1/1/0/) of it.

This is in keeping with the broad principles of the [draft code of conduct](http://indiewebcamp.com/code-of-conduct) already in use by the IndieWeb community.

**Comment by tommorris** [comment]
An alternative to this is to simply adopt the IndieWebCamp code of conduct. This might be easier.

**Comment by kevinmarks** [comment]
django's language is more explicitly inclusive rather than warning: https://www.djangoproject.com/conduct/

**Comment by kylewm** [comment]
These all seem basically good. I like Django's as-is or using IWC's as an opportunity to improve it to cover more project/development-specific cases.

The really challenging part to me is when the bad behavior happens outside of the event/community/site. In the Opal case, someone filed an issue saying a contributor should be removed because he said something transphobic in an @-reply on Twitter, and people argued that that space was outside of the project and Github so was irrelevant -- I wish all three CoC's did more to be explicit about whether they do or do not cover behavior outside the community. Of course, I know it's case-by-case, and bad enough behavior warrants consequence regardless of where it happens.
